

from app.database import SessionLocal, engine
from app.models import Base, Scheme

Base.metadata.create_all(bind=engine)

NEW_SCHEMES = [

    # ─── AGRICULTURE / FARMER ───────────────────────────────────────────────
    Scheme(
        name="Pradhan Mantri Fasal Bima Yojana (PMFBY)",
        ministry="Ministry of Agriculture & Farmers Welfare",
        description="Provides comprehensive crop insurance coverage to farmers against crop failure due to natural calamities, pests and diseases.",
        min_age=18, max_income=None,
        target_occupation="Farmer", target_category="All", state="All",
        benefit="Financial support for crop losses; premium as low as 2% for Kharif crops",
        application_link="https://pmfby.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply through nearest bank branch or Common Service Centre (CSC) before sowing.",
        documents_required="Aadhaar, land records (khasra/khatauni), bank passbook, sowing certificate",
    ),
    Scheme(
        name="Kisan Credit Card (KCC) Scheme",
        ministry="Ministry of Agriculture & Farmers Welfare",
        description="Provides farmers with affordable credit for agricultural needs including cultivation expenses, post-harvest expenses, and maintenance of farm assets.",
        min_age=18, max_income=None,
        target_occupation="Farmer", target_category="All", state="All",
        benefit="Revolving credit facility at concessional interest rates (2–4% effective rate)",
        application_link="https://www.nabard.org/",
        scheme_type="Central",
        how_to_apply="Apply at nearest bank branch with completed KCC application form.",
        documents_required="Aadhaar, land ownership documents, passport-size photo, bank account details",
    ),
    Scheme(
        name="PM Krishi Sinchai Yojana (PMKSY)",
        ministry="Ministry of Agriculture & Farmers Welfare",
        description="Aims to improve on-farm water use efficiency to provide 'More crop per drop' and enhance farm income through micro irrigation.",
        min_age=18, max_income=None,
        target_occupation="Farmer", target_category="All", state="All",
        benefit="Subsidy on micro-irrigation equipment (drip/sprinkler) up to 55% for small farmers",
        application_link="https://pmksy.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply online at PMKSY portal or through district agriculture office.",
        documents_required="Aadhaar, land records, bank account details, quotation from approved vendor",
    ),
    Scheme(
        name="National Agriculture Market (eNAM)",
        ministry="Ministry of Agriculture & Farmers Welfare",
        description="A pan-India electronic trading portal networking existing APMC mandis to create a unified national market for agricultural commodities.",
        min_age=18, max_income=None,
        target_occupation="Farmer", target_category="All", state="All",
        benefit="Better price discovery, transparent auction process, online payment directly to farmer",
        application_link="https://enam.gov.in/",
        scheme_type="Central",
        how_to_apply="Register at local APMC mandi office or online at eNAM portal with Aadhaar and bank details.",
        documents_required="Aadhaar, bank passbook, mobile number",
    ),

    # ─── EDUCATION / STUDENT ────────────────────────────────────────────────
    Scheme(
        name="National Scholarship Portal (NSP) - Central Sector Scheme",
        ministry="Ministry of Education",
        description="Centralized online platform for scholarship applications for meritorious students from economically weaker sections for pursuing higher education.",
        min_age=18, max_income=450000,
        target_occupation="Student", target_category="All", state="All",
        benefit="Rs. 10,000–25,000 per year for undergraduate and postgraduate studies",
        application_link="https://scholarships.gov.in/",
        scheme_type="Central",
        how_to_apply="Register on National Scholarship Portal and fill the scholarship application form online.",
        documents_required="Aadhaar, mark sheets, income certificate, bank account details, domicile certificate",
    ),
    Scheme(
        name="PM YASASVI Scholarship Scheme",
        ministry="Ministry of Social Justice and Empowerment",
        description="Provides scholarships to OBC, EBC and DNT students for pre-matric and post-matric studies to promote education among these communities.",
        min_age=14, max_income=250000,
        target_occupation="Student", target_category="OBC", state="All",
        benefit="Pre-Matric: Rs. 15,000/year; Post-Matric & Top Class: up to Rs. 1,25,000/year",
        application_link="https://scholarships.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply online through National Scholarship Portal during the application window.",
        documents_required="Aadhaar, caste certificate, income certificate, last year mark sheet, bank passbook",
    ),
    Scheme(
        name="Samagra Shiksha Abhiyan",
        ministry="Ministry of Education",
        description="Integrated scheme for school education from pre-primary to senior secondary level to ensure inclusive and equitable quality education.",
        min_age=3, max_income=None,
        target_occupation="Student", target_category="All", state="All",
        benefit="Free books, uniforms, mid-day meals, bicycles for girls, and inclusive education support",
        application_link="https://samagra.education.gov.in/",
        scheme_type="Central",
        how_to_apply="Automatically covered via school enrollment; contact head teacher for specific benefits.",
        documents_required="School enrollment proof, Aadhaar, birth certificate",
    ),
    Scheme(
        name="Skill India Mission - PMKVY",
        ministry="Ministry of Skill Development and Entrepreneurship",
        description="Pradhan Mantri Kaushal Vikas Yojana enables youth to take up industry-relevant skill training to find better livelihoods.",
        min_age=15, max_income=None,
        target_occupation="Student", target_category="All", state="All",
        benefit="Free skill training + Rs. 500/month stipend + placement assistance + certification",
        application_link="https://www.pmkvyofficial.org/",
        scheme_type="Central",
        how_to_apply="Register online at PMKVY portal or visit nearest PMKVY Training Centre.",
        documents_required="Aadhaar, 10th mark sheet, passport-size photo, bank account",
    ),

    # ─── HEALTH ─────────────────────────────────────────────────────────────
    Scheme(
        name="Pradhan Mantri Surakshit Matritva Abhiyan (PMSMA)",
        ministry="Ministry of Health and Family Welfare",
        description="Provides fixed-day, assured, comprehensive and quality antenatal care to pregnant women on the 9th of every month.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="Female", state="All",
        benefit="Free antenatal check-up, blood tests, ultrasound, iron-folic acid tablets",
        application_link="https://pmsma.nhp.gov.in/",
        scheme_type="Central",
        how_to_apply="Visit nearest government health facility or empanelled private clinic on 9th of every month.",
        documents_required="Aadhaar, MCH card (Mother and Child Protection Card)",
    ),
    Scheme(
        name="National Health Mission (NHM)",
        ministry="Ministry of Health and Family Welfare",
        description="Provides accessible, affordable and quality healthcare to rural and urban populations, especially vulnerable groups.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Free primary healthcare, medicines, diagnostics, maternal and child health services",
        application_link="https://nhm.gov.in/",
        scheme_type="Central",
        how_to_apply="Visit nearest government Primary Health Centre (PHC) or Community Health Centre (CHC).",
        documents_required="Aadhaar or any ID proof",
    ),
    Scheme(
        name="Janani Suraksha Yojana (JSY)",
        ministry="Ministry of Health and Family Welfare",
        description="A safe motherhood intervention promoting institutional delivery among poor pregnant women to reduce maternal and neo-natal mortality.",
        min_age=19, max_income=None,
        target_occupation="All", target_category="BPL", state="All",
        benefit="Cash assistance: Rs. 1,400 (rural) and Rs. 1,000 (urban) for institutional delivery",
        application_link="https://nhm.gov.in/index1.php?lang=1&level=3&sublinkid=841&lid=309",
        scheme_type="Central",
        how_to_apply="Register at nearest Anganwadi Centre or government hospital during pregnancy.",
        documents_required="Aadhaar, BPL card, MCH register card, bank account details",
    ),
    Scheme(
        name="PM Jan Arogya Yojana - CGHS Extension",
        ministry="Ministry of Health and Family Welfare",
        description="Central Government Health Scheme providing comprehensive healthcare facilities to central government employees, pensioners and their dependents.",
        min_age=0, max_income=None,
        target_occupation="Government Employee", target_category="All", state="All",
        benefit="Cashless OPD/IPD treatment, specialist consultation, medicines at CGHS wellness centres",
        application_link="https://cghs.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply through department's nodal officer; submit CGHS card application with service details.",
        documents_required="Service certificate, Aadhaar, family details, passport photo",
    ),

    # ─── HOUSING ─────────────────────────────────────────────────────────────
    Scheme(
        name="Pradhan Mantri Awas Yojana - Gramin (PMAY-G)",
        ministry="Ministry of Rural Development",
        description="Provides financial assistance to rural households living in kutcha/dilapidated houses to construct pucca houses with basic amenities.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="BPL", state="All",
        benefit="Rs. 1,20,000 (plains) / Rs. 1,30,000 (hilly/difficult areas) for house construction",
        application_link="https://pmayg.nic.in/",
        scheme_type="Central",
        how_to_apply="Register through Gram Panchayat; selection based on SECC 2011 data.",
        documents_required="Aadhaar, BPL card, bank account, MGNREGS job card (optional)",
    ),
    Scheme(
        name="Credit Linked Subsidy Scheme (CLSS) - PMAY",
        ministry="Ministry of Housing and Urban Affairs",
        description="Provides interest subsidy on home loans to EWS/LIG/MIG beneficiaries for purchase/construction/extension of houses.",
        min_age=18, max_income=1800000,
        target_occupation="All", target_category="EWS/LIG", state="All",
        benefit="Interest subsidy of 6.5% (EWS/LIG), 4% (MIG-I), 3% (MIG-II) on home loans",
        application_link="https://pmaymis.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply through empanelled banks/HFCs; submit CLSS application with home loan request.",
        documents_required="Aadhaar, income proof, property documents, home loan application",
    ),

    # ─── FINANCE / BANKING ──────────────────────────────────────────────────
    Scheme(
        name="PM Jan Dhan Yojana (PMJDY)",
        ministry="Ministry of Finance",
        description="Ensures access to financial services like banking accounts, remittance, credit, insurance and pension to every household.",
        min_age=10, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Zero-balance account, RuPay debit card, Rs. 10,000 overdraft, Rs. 2 lakh accident insurance",
        application_link="https://pmjdy.gov.in/",
        scheme_type="Central",
        how_to_apply="Visit any bank branch with Aadhaar and fill up account opening form.",
        documents_required="Aadhaar or any officially valid document + passport photo",
    ),
    Scheme(
        name="PM Mudra Yojana (PMMY)",
        ministry="Ministry of Finance",
        description="Provides loans up to Rs. 10 lakh to non-corporate, non-farm small/micro enterprises through member lending institutions.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Shishu: up to Rs.50,000 | Kishore: Rs.50,001–5 lakh | Tarun: Rs.5–10 lakh (no collateral)",
        application_link="https://www.mudra.org.in/",
        scheme_type="Central",
        how_to_apply="Apply at any PSU bank, regional rural bank, microfinance institution or NBFC.",
        documents_required="Aadhaar, PAN, business proof, bank statements (6 months), quotation for machinery",
    ),
    Scheme(
        name="PM Jeevan Jyoti Bima Yojana (PMJJBY)",
        ministry="Ministry of Finance",
        description="Annual renewable term life insurance scheme offering life cover of Rs. 2 lakh at a premium of Rs. 436 per year.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Rs. 2 lakh life cover on death for any reason at Rs. 436/year premium",
        application_link="https://financialservices.gov.in/insurance-divisions/Government-Sponsored-Socially-Oriented-Insurance-Schemes/Pradhan-Mantri-Jeevan-Jyoti-Bima-Yojana(PMJJBY)",
        scheme_type="Central",
        how_to_apply="Enroll through bank branch or net banking by giving auto-debit consent.",
        documents_required="Aadhaar, bank account, nominee details",
    ),
    Scheme(
        name="PM Suraksha Bima Yojana (PMSBY)",
        ministry="Ministry of Finance",
        description="Annual accident insurance scheme offering accidental death and disability cover of Rs. 2 lakh at just Rs. 20 per year.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Rs. 2 lakh on accidental death/full disability; Rs. 1 lakh on partial disability",
        application_link="https://financialservices.gov.in/",
        scheme_type="Central",
        how_to_apply="Enroll through bank branch; auto-debit of Rs. 20 from savings account annually.",
        documents_required="Aadhaar, savings bank account",
    ),

    # ─── WOMEN ──────────────────────────────────────────────────────────────
    Scheme(
        name="Pradhan Mantri Matru Vandana Yojana (PMMVY)",
        ministry="Ministry of Women and Child Development",
        description="A maternity benefit program providing cash incentives to pregnant women and lactating mothers for first live birth to compensate wage loss.",
        min_age=19, max_income=None,
        target_occupation="All", target_category="Female", state="All",
        benefit="Rs. 5,000 in three installments for first live birth; Rs. 6,000 for second birth if girl child",
        application_link="https://pmmvy.nic.in/",
        scheme_type="Central",
        how_to_apply="Register at nearest Anganwadi Centre within 150 days of pregnancy.",
        documents_required="Aadhaar, MCP card, bank passbook, institution delivery proof",
    ),
    Scheme(
        name="Beti Bachao Beti Padhao (BBBP)",
        ministry="Ministry of Women and Child Development",
        description="Aims to address the issue of declining child sex ratio and promote welfare and education of the girl child.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="Female", state="All",
        benefit="Awareness programs, conditional cash transfers for girl education, health check-ups",
        application_link="https://wcd.nic.in/bbbp-schemes",
        scheme_type="Central",
        how_to_apply="Contact district Women and Child Development officer for local program enrollment.",
        documents_required="Girl child birth certificate, Aadhaar of parents",
    ),
    Scheme(
        name="One Stop Centre (Sakhi) Scheme",
        ministry="Ministry of Women and Child Development",
        description="Provides integrated support and assistance to women affected by violence in private and public spaces under one roof.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="Female", state="All",
        benefit="Police assistance, medical aid, legal aid, psychological counselling, temporary shelter – all free",
        application_link="https://wcd.nic.in/schemes-listing/2548",
        scheme_type="Central",
        how_to_apply="Call helpline 181 or visit nearest One Stop Centre (located in govt hospitals).",
        documents_required="No documents required; immediate assistance provided",
    ),
    Scheme(
        name="PM Poshan Shakti Nirman (Mid-Day Meal Scheme)",
        ministry="Ministry of Education",
        description="National programme providing hot cooked meals to school children to improve attendance and reduce drop-out especially for girl children.",
        min_age=6, max_income=None,
        target_occupation="Student", target_category="All", state="All",
        benefit="Free nutritious hot meal every school day; 450–700 calories per meal for children",
        application_link="https://pmposhan.education.gov.in/",
        scheme_type="Central",
        how_to_apply="Automatically provided to all children enrolled in government/government-aided schools.",
        documents_required="School enrollment proof",
    ),

    # ─── DISABILITY ──────────────────────────────────────────────────────────
    Scheme(
        name="Unique Disability ID (UDID) Card Scheme",
        ministry="Ministry of Social Justice and Empowerment",
        description="Creates a national database for persons with disabilities and provides a unique disability ID card to avail benefits of various welfare schemes.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="Disability", state="All",
        benefit="Single card for all disability-related benefits; access to over 30 central schemes",
        application_link="https://www.swavlambancard.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply online on UDID portal or through district hospital's medical board.",
        documents_required="Aadhaar, disability certificate from government hospital, passport photo",
    ),
    Scheme(
        name="Assistance to Disabled Persons for Purchase of Aids (ADIP)",
        ministry="Ministry of Social Justice and Empowerment",
        description="Provides modern, durable, scientifically manufactured assistive devices to people with disabilities to restore their physical, social and psychological functions.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="Disability", state="All",
        benefit="Free/subsidized hearing aids, wheelchairs, tricycles, crutches, prosthetic limbs, etc.",
        application_link="https://disabilityaffairs.gov.in/content/page/adip-scheme.php",
        scheme_type="Central",
        how_to_apply="Apply through ALIMCO camps or district disability rehabilitation centres.",
        documents_required="UDID card / disability certificate, income proof, Aadhaar",
    ),
    Scheme(
        name="National Scholarship for Persons with Disabilities",
        ministry="Ministry of Social Justice and Empowerment",
        description="Scholarships for students with disabilities pursuing pre-matric, post-matric and top class education.",
        min_age=0, max_income=250000,
        target_occupation="Student", target_category="Disability", state="All",
        benefit="Pre-Matric: Rs. 500–1,000/month; Post-Matric: up to Rs. 13,500/month + book allowance",
        application_link="https://scholarships.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply through National Scholarship Portal during the application period.",
        documents_required="UDID card, income certificate, mark sheets, bank passbook, Aadhaar",
    ),

    # ─── SENIOR CITIZENS / RETIRED ──────────────────────────────────────────
    Scheme(
        name="Pradhan Mantri Vaya Vandana Yojana (PMVVY)",
        ministry="Ministry of Finance",
        description="A pension scheme for senior citizens providing assured pension/return based on purchase price giving 7.4% per annum guaranteed returns.",
        min_age=60, max_income=None,
        target_occupation="Retired", target_category="All", state="All",
        benefit="Guaranteed pension of Rs. 1,000–9,250/month; 10-year policy term via LIC",
        application_link="https://licindia.in/Home/Products/Pension-Plans",
        scheme_type="Central",
        how_to_apply="Purchase online or offline through LIC of India branches.",
        documents_required="Aadhaar, PAN, bank account details, age proof",
    ),
    Scheme(
        name="Indira Gandhi National Old Age Pension Scheme (IGNOAPS)",
        ministry="Ministry of Rural Development",
        description="Provides pension to below poverty line elders aged 60 years and above under the National Social Assistance Programme.",
        min_age=60, max_income=None,
        target_occupation="All", target_category="BPL", state="All",
        benefit="Rs. 200/month (60–79 years); Rs. 500/month (80+ years)",
        application_link="https://nsap.nic.in/",
        scheme_type="Central",
        how_to_apply="Apply at Gram Panchayat/Block Development Office with BPL ration card.",
        documents_required="Aadhaar, BPL ration card, age proof, bank passbook",
    ),
    Scheme(
        name="Senior Citizens Savings Scheme (SCSS)",
        ministry="Ministry of Finance",
        description="A government-backed savings scheme for Indian citizens aged 60 and above offering high interest rates and safety of investment.",
        min_age=60, max_income=None,
        target_occupation="Retired", target_category="All", state="All",
        benefit="8.2% interest per annum with quarterly payout; maximum deposit Rs. 30 lakh",
        application_link="https://www.indiapost.gov.in/",
        scheme_type="Central",
        how_to_apply="Open account at Post Office or authorized bank; min deposit Rs. 1,000.",
        documents_required="Aadhaar, PAN, age proof, passport photo, cheque/DD",
    ),

    # ─── EMPLOYMENT / SKILLS / UNEMPLOYED ───────────────────────────────────
    Scheme(
        name="Mahatma Gandhi National Rural Employment Guarantee (MGNREGS)",
        ministry="Ministry of Rural Development",
        description="Guarantees 100 days of wage employment per year to every rural household willing to do unskilled manual work.",
        min_age=18, max_income=None,
        target_occupation="Unemployed", target_category="All", state="All",
        benefit="Minimum wage (Rs. 204–322/day depending on state) for unskilled work; unemployment allowance if work not given",
        application_link="https://nrega.nic.in/",
        scheme_type="Central",
        how_to_apply="Register at Gram Panchayat office to get Job Card; request for work through written application.",
        documents_required="Aadhaar, bank/post office account, passport photo, residential proof",
    ),
    Scheme(
        name="PM Rozgar Protsahan Yojana (PMRPY)",
        ministry="Ministry of Labour and Employment",
        description="Government pays full employer's contribution (12%) to EPF and EPS for new employees for 3 years to incentivize hiring.",
        min_age=18, max_income=None,
        target_occupation="Unemployed", target_category="All", state="All",
        benefit="Full EPF/EPS contribution by government for 3 years on new employee hiring",
        application_link="https://pmrpy.gov.in/",
        scheme_type="Central",
        how_to_apply="Employers register on PMRPY portal and link EPFO registration.",
        documents_required="EPFO registration, new employee Aadhaar-linked UAN",
    ),
    Scheme(
        name="Atmanirbhar Bharat Rozgar Yojana (ABRY)",
        ministry="Ministry of Labour and Employment",
        description="Incentivizes employers to create new employment opportunities and support creation of new jobs during COVID-19 recovery.",
        min_age=18, max_income=None,
        target_occupation="Unemployed", target_category="All", state="All",
        benefit="Government subsidizes EPF contributions (12% employee + 12% employer) for 2 years on new hires",
        application_link="https://www.epfindia.gov.in/",
        scheme_type="Central",
        how_to_apply="EPFO-registered employers can claim through their EPFO account.",
        documents_required="EPFO registration, new employee Aadhaar-UAN linkage",
    ),

    # ─── SOCIAL WELFARE / SC / OBC / BPL ────────────────────────────────────
    Scheme(
        name="Post Matric Scholarship for SC Students",
        ministry="Ministry of Social Justice and Empowerment",
        description="Provides financial assistance to SC students pursuing post-matric or post-secondary education to enable them to complete education.",
        min_age=14, max_income=250000,
        target_occupation="Student", target_category="SC", state="All",
        benefit="Maintenance allowance Rs. 380–1,200/month + course fees reimbursement",
        application_link="https://scholarships.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply on National Scholarship Portal within deadline; get verified by institution.",
        documents_required="SC caste certificate, income certificate, mark sheets, Aadhaar, bank passbook",
    ),
    Scheme(
        name="Pre Matric Scholarship for SC/ST Students",
        ministry="Ministry of Tribal Affairs / Social Justice",
        description="Encourages parents from SC/ST communities to send their children to school by providing financial assistance for education expenses.",
        min_age=9, max_income=250000,
        target_occupation="Student", target_category="SC", state="All",
        benefit="Day Scholar: Rs. 150–250/month + ad-hoc grant Rs. 500/year",
        application_link="https://scholarships.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply through school after enrollment; submit to state social welfare department.",
        documents_required="Caste certificate, income certificate, school enrollment letter, Aadhaar",
    ),
    Scheme(
        name="National SC Finance and Development Corporation (NSFDC) Loan",
        ministry="Ministry of Social Justice and Empowerment",
        description="Provides concessional finance for income-generating activities to persons belonging to Scheduled Castes below double the poverty line.",
        min_age=18, max_income=300000,
        target_occupation="All", target_category="SC", state="All",
        benefit="Loans at 2% (women) to 6% interest for self-employment projects up to Rs. 15 lakh",
        application_link="https://nsfdc.nic.in/",
        scheme_type="Central",
        how_to_apply="Apply through State Channelising Agencies (SCA) of respective state.",
        documents_required="SC caste certificate, income proof, project report, Aadhaar, bank account",
    ),

    # ─── DIGITAL INDIA / IT / TECHNOLOGY ────────────────────────────────────
    Scheme(
        name="PM Gramin Digital Saksharta Abhiyan (PMGDISHA)",
        ministry="Ministry of Electronics and Information Technology",
        description="Aims to make 6 crore rural households digitally literate to enable them to operate computers/smartphones and use internet services.",
        min_age=14, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Free digital literacy training; certificate recognized by NIELIT/CSC",
        application_link="https://www.pmgdisha.in/",
        scheme_type="Central",
        how_to_apply="Register at nearest Common Service Centre (CSC) or online at PMGDISHA portal.",
        documents_required="Aadhaar, passport photo",
    ),
    Scheme(
        name="Startup India Seed Fund Scheme",
        ministry="Ministry of Commerce and Industry",
        description="Provides financial assistance to startups for proof of concept, prototype development, product trials, market entry and commercialization.",
        min_age=21, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Seed funding up to Rs. 20 lakh for PoC/prototype; up to Rs. 50 lakh for market entry",
        application_link="https://seedfund.startupindia.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply online at Startup India portal; must be DPIIT-recognized startup.",
        documents_required="DPIIT registration certificate, business plan, Aadhaar/PAN, incorporation certificate",
    ),
    Scheme(
        name="BharatNet Project",
        ministry="Ministry of Communications",
        description="Provides broadband connectivity to all Gram Panchayats in India through optical fibre cable to bridge the digital divide.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="High-speed broadband (100 Mbps) at affordable rates available at village-level WiFi hotspots",
        application_link="https://bbnl.nic.in/",
        scheme_type="Central",
        how_to_apply="Access available at Common Service Centres in Gram Panchayats; no individual application needed.",
        documents_required="No specific documents required",
    ),

    # ─── STATE SCHEMES (representative examples) ─────────────────────────────
    Scheme(
        name="Ladli Behna Yojana (Madhya Pradesh)",
        ministry="Government of Madhya Pradesh",
        description="Provides monthly financial assistance to women in Madhya Pradesh to strengthen their economic independence.",
        min_age=21, max_income=None,
        target_occupation="All", target_category="Female", state="Madhya Pradesh",
        benefit="Rs. 1,250/month directly transferred to bank account",
        application_link="https://cmladlibahna.mp.gov.in/",
        scheme_type="State",
        how_to_apply="Apply online or at nearest Gram Panchayat/Ward office during camp registration.",
        documents_required="Aadhaar, Samग्र ID, bank account, mobile number",
    ),
    Scheme(
        name="Amma Vodi (Andhra Pradesh)",
        ministry="Government of Andhra Pradesh",
        description="Provides financial assistance to mothers who send children to school as an incentive for education in Andhra Pradesh.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="Female", state="Andhra Pradesh",
        benefit="Rs. 15,000 per year per mother sending children to school",
        application_link="https://ammavodi.ap.gov.in/",
        scheme_type="State",
        how_to_apply="Enroll through school; mother's details linked via child's Aadhaar.",
        documents_required="Aadhaar of mother and child, school enrollment certificate, bank passbook",
    ),
    Scheme(
        name="Rythu Bandhu (Telangana)",
        ministry="Government of Telangana",
        description="Investment support scheme providing financial assistance to farmers per acre of land per crop season in Telangana.",
        min_age=18, max_income=None,
        target_occupation="Farmer", target_category="All", state="Telangana",
        benefit="Rs. 5,000 per acre per crop season (Rs. 10,000 per year) directly to farmer",
        application_link="https://rythubandhu.telangana.gov.in/",
        scheme_type="State",
        how_to_apply="Automatically credited based on Dharani portal land records.",
        documents_required="Pattadar Passbook, Aadhaar-linked bank account",
    ),

    # ─── SPORTS & CULTURE ────────────────────────────────────────────────────
    Scheme(
        name="Khelo India Scheme",
        ministry="Ministry of Youth Affairs and Sports",
        description="Reviving sports culture at grassroots level in India through investment in youth sports talent identification and annual sports scholarship.",
        min_age=8, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Annual scholarship of Rs. 5 lakh for 8 years for identified talent; free coaching and equipment",
        application_link="https://kheloindia.gov.in/",
        scheme_type="Central",
        how_to_apply="Participate in Khelo India Games; top performers are selected for scholarships.",
        documents_required="Age proof, sports achievement certificate, Aadhaar, bank account",
    ),

    # ─── TRANSPORT & INFRASTRUCTURE ──────────────────────────────────────────
    Scheme(
        name="PM Gram Sadak Yojana (PMGSY)",
        ministry="Ministry of Rural Development",
        description="Provides all-weather road connectivity to unconnected habitations as part of a poverty reduction strategy for rural areas.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="All-weather road access connecting rural habitations to markets, schools and hospitals",
        application_link="https://pmgsy.nic.in/",
        scheme_type="Central",
        how_to_apply="Village councils/Gram Panchayats apply through DPR submission to district authority.",
        documents_required="Village connectivity status report, population certificate",
    ),

    # ─── UTILITY / SANITATION ────────────────────────────────────────────────
    Scheme(
        name="Swachh Bharat Mission - Gramin (SBM-G)",
        ministry="Ministry of Jal Shakti",
        description="Aims to make India open-defecation free and improve solid and liquid waste management in rural areas through toilet construction.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Incentive of Rs. 12,000 for construction of individual household latrine (IHHL)",
        application_link="https://swachhbharatmission.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply through Gram Panchayat or block development office.",
        documents_required="Aadhaar, bank account, BPL card or ration card",
    ),
    Scheme(
        name="Jal Jeevan Mission (Har Ghar Jal)",
        ministry="Ministry of Jal Shakti",
        description="Provides safe and adequate drinking water through individual tap connections to every rural household by 2024.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Functional Household Tap Connection (FHTC) providing 55 litres per person per day",
        application_link="https://jaljeevanmission.gov.in/",
        scheme_type="Central",
        how_to_apply="Village Water & Sanitation Committee (VWSC) facilitates connection; contact Gram Panchayat.",
        documents_required="Residential proof, Aadhaar",
    ),
    Scheme(
        name="PM Ujjwala Yojana (PMUY)",
        ministry="Ministry of Petroleum and Natural Gas",
        description="Provides free LPG connections to women from Below Poverty Line (BPL) households to replace unhealthy cooking fuels.",
        min_age=18, max_income=None,
        target_occupation="All", target_category="BPL", state="All",
        benefit="Free LPG connection + first refill free + EMI option for stove and first refill",
        application_link="https://pmuy.gov.in/",
        scheme_type="Central",
        how_to_apply="Apply at nearest LPG distributor or online at MyLPG portal.",
        documents_required="Aadhaar, BPL ration card, bank account, passport photo",
    ),

    # ─── TRAVEL & TOURISM ─────────────────────────────────────────────────────
    Scheme(
        name="Swadesh Darshan Scheme",
        ministry="Ministry of Tourism",
        description="Integrated development of theme-based tourist circuits in India to promote religious, heritage, eco and other forms of tourism.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Developed tourist circuits with infrastructure; enhanced visitor experience at pilgrimage and heritage sites",
        application_link="https://tourism.gov.in/swadesh-darshan-scheme",
        scheme_type="Central",
        how_to_apply="Scheme is for infrastructure development; tourists benefit from improved sites.",
        documents_required="Not applicable for tourists",
    ),
    Scheme(
        name="Prasad Scheme (Pilgrimage Rejuvenation and Spiritual Augmentation Drive)",
        ministry="Ministry of Tourism",
        description="Focuses on integrated development of pilgrimage sites to enhance religious tourism experience across India.",
        min_age=0, max_income=None,
        target_occupation="All", target_category="All", state="All",
        benefit="Improved services, waiting halls, sanitization, signages and facilities at pilgrimage sites",
        application_link="https://tourism.gov.in/prasad-scheme",
        scheme_type="Central",
        how_to_apply="Infrastructure project; pilgrims benefit automatically at developed sites.",
        documents_required="Not applicable",
    ),
]


def add_schemes():
    db = SessionLocal()
    added = 0
    skipped = 0
    try:
        existing_names = {s.name for s in db.query(Scheme.name).all()}
        for scheme in NEW_SCHEMES:
            if scheme.name in existing_names:
                print(f"  ⏭  Skipping (already exists): {scheme.name}")
                skipped += 1
            else:
                db.add(scheme)
                print(f"  ✅ Adding: {scheme.name}")
                added += 1
        db.commit()
        print(f"\n🎉 Done! Added {added} new schemes, skipped {skipped} duplicates.")
    except Exception as e:
        db.rollback()
        print(f"❌ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    add_schemes()
